project:
  type: website
  resources:
    - "data/*"

website:
  title: "Taylor Swift Album Gallery"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



